apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Engedélyezzük az AOF módot
    appendonly no
    save 900 1
    save 300 10
    save 60 10000
    # Adattároló könyvtár
    dir /data
