apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # RDB snapshot mód engedélyezése
    appendonly no
    # Ha legalább 1 változás történik 1 másodperc alatt, készít snapshotot
    save 1 1
    # Beállítja az adattároló könyvtárat
    dir /data
