apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: manual
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/user/redis/data
